services:
  ros2_dev:
    network_mode: host
    build:
      network: host
      context: .
      args:
        DIR: "${DIR}"
    working_dir: /${DIR}
    volumes:
      - ./:/${DIR}

    tty: true
    command: bash